<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 物理参数定义 -->
    <xacro:property name="chassis_length" value="0.63" />  <!-- 63cm -->
    <xacro:property name="chassis_width" value="0.40" />   <!-- 40cm -->
    <xacro:property name="chassis_height" value="0.20" />  <!-- 40cm -->
    
    <xacro:property name="wheel_radius" value="0.065" />   <!-- 13cm直径，半径6.5cm -->
    <xacro:property name="wheel_thickness" value="0.14" />
    <xacro:property name="wheel_mass" value="3.0" />
    <xacro:property name="steering_mass" value="0.01" />
    <xacro:property name="body_mass" value="25.0" />

    <!-- 轮子位置计算 -->
    <!-- 前轮距离最前方6cm，后轮距离最后方4cm -->
    <xacro:property name="front_wheel_x" value="${chassis_length/2 - 0.06}" />  <!-- 0.255m -->
    <xacro:property name="rear_wheel_x" value="${-chassis_length/2 + 0.04}" />  <!-- -0.275m -->
    <xacro:property name="wheel_y" value="${chassis_width/2}" />  <!-- 0.20m -->

    <!-- BASE FOOTPRINT -->
    <link name="base_footprint">
        <origin xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="base_link">
        <inertial>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
            <mass value="${body_mass}" />
            <inertia ixx="${body_mass/12 * (chassis_width*chassis_width + chassis_height*chassis_height)}"
                ixy="0" ixz="0"
                iyy="${body_mass/12 * (chassis_length*chassis_length + chassis_height*chassis_height)}" 
                iyz="0"
                izz="${body_mass/12 * (chassis_length*chassis_length + chassis_width*chassis_width)}" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <material name="black">
                <color rgba="0.15 0.15 0.15 1.0" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
    </link>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0 0 0" />
    </joint>

    <!-- FRONT LEFT WHEEL -->
    <link name="fr_left_steer_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${steering_mass}" />
            <inertia
                ixx="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${steering_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
    </link>
    <joint name="fr_left_steer_joint" type="revolute">
        <origin xyz="${front_wheel_x} ${wheel_y} ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="fr_left_steer_link" />
        <axis xyz="0 0 1" />
        <limit upper="0.6" lower="-0.6" effort="-1.0" velocity="-1.0" />
    </joint>
    <link name="fr_left_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia
                ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="">
                <color rgba="0.223529411764706 0.223529411764706 0.223529411764706 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>
    </link>
    <joint name="fr_left_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="fr_left_steer_link" />
        <child link="fr_left_wheel_link" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.8" damping="0.5" />
        <limit lower="-3.14159" upper="3.14159" effort="200" velocity="-1" />
    </joint>

    <!-- FRONT RIGHT WHEEL -->
    <link name="fr_right_steer_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${steering_mass}" />
            <inertia
                ixx="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${steering_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
    </link>
    <joint name="fr_right_steer_joint" type="revolute">
        <origin xyz="${front_wheel_x} ${-wheel_y} ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="fr_right_steer_link" />
        <axis xyz="0 0 1" />
        <limit upper="0.6" lower="-0.6" effort="-1.0" velocity="-1.0" />
    </joint>
    <link name="fr_right_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia
                ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="">
                <color rgba="0.223529411764706 0.223529411764706 0.223529411764706 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>
    </link>
    <joint name="fr_right_wheel_joint" type="continuous">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="fr_right_steer_link" />
        <child link="fr_right_wheel_link" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.8" damping="0.5" />
        <limit lower="-3.14159" upper="3.14159" effort="200" velocity="-1" />
    </joint>

    <!-- REAR LEFT WHEEL -->
    <link name="re_left_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia
                ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="">
                <color rgba="0.37647 0.37647 0.37647 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>
    </link>
    <joint name="re_left_wheel_joint" type="continuous">
        <origin xyz="${rear_wheel_x} ${wheel_y} ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="re_left_wheel_link" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.8" damping="0.5" />
        <limit lower="-3.14159" upper="3.14159" effort="70" velocity="-1" />
    </joint>

    <!-- REAR RIGHT WHEEL -->
    <link name="re_right_wheel_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="${wheel_mass}" />
            <inertia
                ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                ixy="0" ixz="0"
                iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"
                iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
            <material name="">
                <color rgba="0.37647 0.37647 0.37647 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="1.5708 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>
    </link>
    <joint name="re_right_wheel_joint" type="continuous">
        <origin xyz="${rear_wheel_x} ${-wheel_y} ${wheel_radius}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="re_right_wheel_link" />
        <axis xyz="0 1 0" />
        <dynamics friction="0.8" damping="0.5" />
        <limit lower="-3.14159" upper="3.14159" effort="70" velocity="-1" />
    </joint>

    <!-- CAMERA: 前轮水平位置，宽度一半处（y=0） -->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.03 0.05 0.03"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="red">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.03 0.05 0.03"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.1"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin rpy="0 0 0" xyz="${front_wheel_x} 0 ${chassis_height}"/>
    </joint>

    <!-- LASER: 摄像头往后3cm -->
    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder length="0.03" radius="0.075"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -0.01"/>
            <material name="rgba(255,255,255,1)">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.03" radius="0.075"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 -0.01"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.2"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
    <joint name="laser_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_link"/>
        <origin rpy="0 0 0" xyz="${front_wheel_x - 0.03} 0 ${chassis_height}"/>
    </joint>

    <!-- IMU -->
    <link name="imu_link">
        <visual>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="rgba(255,255,255,1)">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.05"/>
            <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin rpy="0 0 0" xyz="0 0 ${chassis_height/2}"/>
    </joint>

</robot>
