<?xml version="1.0"?>
<robot name="tianbot_ackermann" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 实际尺寸参数 -->
  <xacro:property name="chassis_length" value="0.63"/>
  <xacro:property name="chassis_width" value="0.40"/>
  <xacro:property name="chassis_height" value="0.40"/>

  <xacro:property name="wheel_radius" value="0.065"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="3.0"/>
  <xacro:property name="steering_mass" value="0.01"/>

  <!-- 轮子位置：前轮距前端6cm，后轮距后端4cm -->
  <xacro:property name="front_wheel_x" value="${chassis_length/2 - 0.06}"/>
  <xacro:property name="rear_wheel_x" value="${-chassis_length/2 + 0.04}"/>
  <xacro:property name="wheel_y" value="${chassis_width/2}"/>

  <xacro:property name="wheelbase" value="${front_wheel_x - rear_wheel_x}"/>
  <xacro:property name="track_width" value="${chassis_width}"/>

  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <!-- Base Footprint -->
  <link name="base_footprint"/>

  <!-- Base Link -->
  <link name="base_link"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Chassis Link -->
  <link name="chassis_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <mass value="15.0"/>
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.8" iyz="0.0" izz="0.5"/>
    </inertial>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- 前轮转向宏 -->
  <xacro:macro name="front_wheel" params="prefix reflect">
    <joint name="${prefix}_steer_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="${prefix}_steer_link"/>
      <origin xyz="${front_wheel_x} ${reflect*wheel_y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <!-- <limit lower="-0.6" upper="0.6" effort="-1.0" velocity="-1.0"/> -->
      <limit lower="-0.6" upper="0.6" effort="100" velocity="-1.0"/>
    </joint>

    <link name="${prefix}_steer_link">
      <inertial>
        <mass value="${steering_mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 ixy="0" ixz="0"
                 iyy="${steering_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 iyz="0"
                 izz="${steering_mass/2 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${prefix}_steer_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.5" friction="0.8"/>
      <!-- <limit lower="-3.14159" upper="3.14159" effort="200" velocity="-1"/> -->
    </joint>

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 ixy="0" ixz="0"
                 iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 iyz="0"
                 izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- 后轮宏 -->
  <xacro:macro name="rear_wheel" params="prefix reflect">
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${rear_wheel_x} ${reflect*wheel_y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.5" friction="0.8"/>
      <!-- <limit lower="-3.14159" upper="3.14159" effort="70" velocity="-1"/> -->
    </joint>

    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 ixy="0" ixz="0"
                 iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
                 iyz="0"
                 izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <!-- 实例化轮子 -->
  <xacro:front_wheel prefix="fr_left" reflect="1"/>
  <xacro:front_wheel prefix="fr_right" reflect="-1"/>
  <xacro:rear_wheel prefix="re_left" reflect="1"/>
  <xacro:rear_wheel prefix="re_right" reflect="-1"/>

  <!-- Gazebo材质与摩擦配置 -->
  <gazebo reference="chassis_link">
    <material>Gazebo/White</material>
    <mu1>0.5</mu1>
    <mu2>0.5</mu2>
  </gazebo>

  <gazebo reference="fr_left_wheel">
    <material>Gazebo/Grey</material>
    <mu1>150.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="fr_right_wheel">
    <material>Gazebo/Grey</material>
    <mu1>150.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="re_left_wheel">
    <material>Gazebo/Grey</material>
    <mu1>150.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="re_right_wheel">
    <material>Gazebo/Grey</material>
    <mu1>150.0</mu1>
    <mu2>10.0</mu2>
  </gazebo>

  <gazebo reference="virtual_steer_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <!-- 摄像头：前轮水平位置，宽度一半处 -->
  <joint name="camera_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="camera_link"/>
    <origin xyz="${front_wheel_x} 0 ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.03 0.05 0.03"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.05 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- 雷达：摄像头往后3cm -->
  <joint name="laser_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="laser_link"/>
    <origin xyz="${front_wheel_x - 0.03} 0 ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <gazebo reference="laser_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="laser_link">
    <sensor name="laser_sensor" type="ray">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <update_rate>50</update_rate>
      <pose>0 0 0.2 0 0 0</pose>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1.000000</resolution>
            <min_angle>0.000000</min_angle>
            <max_angle>6.280000</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.120000</min>
          <max>10.5</max>
          <resolution>0.015000</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>

      <plugin name="laserscan" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

  <joint name="imu_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <gazebo reference="imu_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>/</namespace>
          <remapping>~/out:=imu</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <imu>
        <angular_velocity>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- Virtual Steering wheel -->
  <link name="virtual_steer_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="0.01 0.15 0.075"/>
      </geometry>
      <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <inertial>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <mass value="0.001"/>
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
    </inertial>
  </link>

  <joint name="virtual_steering_wheel_joint" type="revolute">
    <origin xyz="${-chassis_length/2 + 0.1} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="chassis_link"/>
    <child link="virtual_steer_link"/>
    <axis xyz="-1 0 0"/>
    <limit lower="-3" upper="3" effort="200" velocity="20"/>
  </joint>

  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher"
            filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>100</update_rate>
      <joint_name>fr_right_steer_joint</joint_name>
      <joint_name>fr_right_wheel_joint</joint_name>
      <joint_name>fr_left_steer_joint</joint_name>
      <joint_name>fr_left_wheel_joint</joint_name>
      <joint_name>re_right_wheel_joint</joint_name>
      <joint_name>re_left_wheel_joint</joint_name>
      <joint_name>virtual_steering_wheel_joint</joint_name>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_joint_pose_trajectory"
            filename="libgazebo_ros_joint_pose_trajectory.so">
      <update_rate>2</update_rate>
    </plugin>
  </gazebo>

  <!-- Gazebo Ackermann插件 -->
  <gazebo>
    <plugin name="gazebo_ackermann_drive" filename="libgazebo_ros_ackermann_drive.so">
      <ros>
        <!-- <namespace>ugv_gazebo_ackermann</namespace> -->
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
        <remapping>distance:=distance</remapping>
      </ros>

      <update_rate>100.0</update_rate>

      <!-- wheels -->
      <front_left_joint>fr_left_wheel_joint</front_left_joint>
      <front_right_joint>fr_right_wheel_joint</front_right_joint>
      <rear_left_joint>re_left_wheel_joint</rear_left_joint>
      <rear_right_joint>re_right_wheel_joint</rear_right_joint>
      <left_steering_joint>fr_left_steer_joint</left_steering_joint>
      <right_steering_joint>fr_right_steer_joint</right_steering_joint>
      <steering_wheel_joint>virtual_steering_wheel_joint</steering_wheel_joint>

      <!-- Max absolute steer angle for tyre in radians-->
      <!-- Any cmd_vel angular z greater than this would be capped -->
      <max_steer>0.383972</max_steer>
      <!-- Max absolute steering angle of steering wheel -->
      <max_steering_angle>1.570796</max_steering_angle>
      <!-- Max absolute linear speed in m/s -->
      <max_speed>5</max_speed>

      <!-- PID tuning -->
      <left_steering_pid_gain>1500 0 1</left_steering_pid_gain>
      <left_steering_i_range>0 0</left_steering_i_range>
      <right_steering_pid_gain>1500 0 1</right_steering_pid_gain>
      <right_steering_i_range>0 0</right_steering_i_range>
      <linear_velocity_pid_gain>1500 0 1</linear_velocity_pid_gain>
      <linear_velocity_i_range>0 0</linear_velocity_i_range>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>     <!-- Don't publish this when using robot localization -->
      <publish_wheel_tf>false</publish_wheel_tf>  <!-- Don't publish this. It will override all wheel frames to robot_base_frame parameter below.-->
      <publish_distance>true</publish_distance>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

</robot>
